[package]
name = "climb-log"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.14.0"
futures = "0.3.30"
itertools = "0.13.0"
sea-orm = { version = "^0.12.0", features = [ "sqlx-sqlite", "runtime-async-std-native-tls", "macros" ] }
tokio = { version = "1.21.2", features = ["full"] }