//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "routes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub length: i32,
    pub pitches: i32,
    pub style: String,
    pub grade_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::grades::Entity",
        from = "Column::GradeId",
        to = "super::grades::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Grades,
    #[sea_orm(has_many = "super::sends::Entity")]
    Sends,
}

impl Related<super::grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Grades.def()
    }
}

impl Related<super::sends::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sends.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
